export const sectionsOrder = [
  "Markdown Languages",
  "Programming languages",
  "Javascript libraries",
  "Mobile frameworks",
  "PHP frameworks",
  "React Native Libraries",
  "Form libraries",
  "State management libraries",
  "Fetching libraries",
  "UI libraries",
  "Data visualization",
  "Animations libraries",
  "Testing frameworks and tools",
  "Internationalization",
  "Maps",
  "Backend technologies",
  "Cloud",
  "Databases",
  "CMS",
  "Payment tools",
  "Web services",
  "Authorization tools",
  "Containerization",
  "Web 3",
  "Analytics",
  "Security",
  "CI CD",
  "Speech recognition",
  "Virtualization",
  "Documentation",
  "Logging tools",
  "Performance monitoring tools",
  "Module bundlers",
  "Graphic editors",
  "Not found",
];
