export const TESTING_FRAMEWORKS_AND_TOOLS = [
  "Detox",
  "Enzyme",
  "Instabug",
  "Jasmine",
  "Jest",
  "Karma",
  "Mocha",
  "Puppeteer",
  "React-testing-library",
  "Storybook",
  "TestFlight",
  "Vitest",
  "Cypress",
  "Sentry",
  "Playwright",
];
