export const UI_LIBRARIES = [
  "СSS3",
  "Styled-components",
  "React Native Elements",
  "React Native Paper",
  "MaterialUI",
  "MUI",
  "SASS",
  "SCSS",
  "Bootstrap",
  "Less",
  "Semantic UI",
  "Chakra UI",
  "Ant-Design",
];
