export const UI_LIBRARIES = [
  "CSS3",
  "CSS",
  "Styled-components",
  "React Native Elements",
  "React Native Paper",
  "MaterialUI",
  "MUI",
  "SASS",
  "SCSS",
  "Bootstrap",
  "Less",
  "Semantic UI",
  "Chakra UI",
  "Ant-Design",
  "Antd",
  "React-table",
  "Tailwind",
  "Devextreme React",
  "React Native Web",
  "CSS Modules",
  "SCSS Modules",
];
